version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: "dockerLoginPassword"
    CLIENTID: "SparkOAuthClientID"
    CLIENTSECRET: "SparkOAuthClientSecret"
    
phases:
  pre_build:
    commands:
      - touch pre_build.file
      - touch .env
      - echo "CLIENTID=" $CLIENTID >> .env
      - echo "CLIENTSEC=" $CLIENTSECRET >> .env
  build:
    commands:
      - npm install
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
